#+TITLE: Heating Simulator

Tool to backtest heat pump performance on real temperature data
* Method
The heat pump is modelled based on several working points from the datasheet,
i.e. combinations of air and water temperature as well as the corresponding COP.
Other values are modelled as the theoretical COP multiplied by the ratio of actual
over theoretical COP at the nearest working point.
* Configuration
** Heatpumps
Heatpump performance is defined in a ~toml~ file, defining a list of working points
(i.e. air and flow temperature with the respective COP) and the maximum electric power.
Temperatures are given in °C, the electric power in kW.
#+BEGIN_SRC toml
working_points = [
            {t_water = 35, t_air = 2, cop = 4},
            {cop = 5.1, t_water = 35, t_air = 7},
            ...
    ]
max_electric = 2.3
#+END_SRC
** Heatloads
A different configuration file defines the properties of the heating system.
In particular, this means how much heat is required at the reference temperature.
It is assumed that above 15 °C, no heating is needed. This can be optionally customized
via the ~cutoff_temperature~ variable.
The required heat is rising linearly below the cutoff temperature.
For the moment, the flow temperature is assumed to be constant.

TODO: Implement an optional curve for the flow temperature.

#+BEGIN_SRC toml
heatload = 10
reference_temperature = -10
cutoff_temperature = 15
flow_temperature = 35
#+END_SRC
